apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 445855602470.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 445855602470.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 510687f9
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
